### ISSUE TITLE
Executing webpack command leads to error

### ISSUE THREAD

**Issue by frankbolviken** [reanimatter/extjs-react-redux#1]
ERROR in ./src/index.jsx
Module build failed: SyntaxError: Unexpected token (22:12)

```
         ReactDOM.render(
             <Provider store={createStoreWithMiddleware(reducers)}>
             ^
                 <App/>
            </Provider>,
             node
```

 @ multi main

**Comment by reanimatter** [comment]
Can you add `test: /\.(js|jsx)$/,` to the babel loader in `webpack.config.js` and see if it helps?

**Comment by frankbolviken** [comment]
I got it working. Had to add query presets :)
